// RBAC Permission Template Seed Data
// This data provides pre-configured permission templates for common roles

export const RBAC_PERMISSION_TEMPLATES = [
  {
    templateCode: 'TEMPLATE_HR_MANAGER_FULL',
    templateName: 'HR Manager - Full Access',
    templateDescription: 'Complete HR management permissions including employee data, recruitment, performance, and reporting',
    templateCategory: 'HR_MANAGEMENT',
    icon: 'UserCheck',
    color: 'blue',
    displayOrder: 1,
    isSystemTemplate: true,
    isRecommended: true,
    permissions: [
      {
        module: 'EMPLOYEE_CENTRAL',
        subModule: 'PERSONAL_DATA',
        permissions: ['EC_PERSONAL_VIEW', 'EC_PERSONAL_EDIT', 'EC_PERSONAL_EXPORT'],
        dataScope: 'DEPARTMENT',
      },
      {
        module: 'EMPLOYEE_CENTRAL',
        subModule: 'EMPLOYMENT_INFO',
        permissions: ['EC_EMPLOYMENT_VIEW', 'EC_EMPLOYMENT_EDIT', 'EC_EMPLOYMENT_APPROVE'],
        dataScope: 'DEPARTMENT',
      },
      {
        module: 'RECRUITING',
        subModule: 'JOB_POSTINGS',
        permissions: ['REC_JOBPOST_VIEW', 'REC_JOBPOST_CREATE', 'REC_JOBPOST_EDIT', 'REC_JOBPOST_APPROVE'],
        dataScope: 'BUSINESS_UNIT',
      },
      {
        module: 'RECRUITING',
        subModule: 'CANDIDATES',
        permissions: ['REC_CANDIDATE_VIEW', 'REC_CANDIDATE_EDIT', 'REC_CANDIDATE_EXPORT'],
        dataScope: 'BUSINESS_UNIT',
      },
      {
        module: 'PERFORMANCE',
        subModule: 'GOAL_MANAGEMENT',
        permissions: ['PERF_GOAL_VIEW', 'PERF_GOAL_APPROVE'],
        dataScope: 'DEPARTMENT',
      },
      {
        module: 'ANALYTICS',
        permissions: ['ANALYTICS_HR_VIEW', 'ANALYTICS_HR_EXPORT'],
        dataScope: 'BUSINESS_UNIT',
      },
    ],
  },
  {
    templateCode: 'TEMPLATE_LINE_MANAGER',
    templateName: 'Line Manager - Team Management',
    templateDescription: 'Standard permissions for managing direct reports and team operations',
    templateCategory: 'MANAGEMENT',
    icon: 'Users',
    color: 'green',
    displayOrder: 2,
    isSystemTemplate: true,
    isRecommended: true,
    permissions: [
      {
        module: 'EMPLOYEE_CENTRAL',
        subModule: 'PERSONAL_DATA',
        permissions: ['EC_PERSONAL_VIEW'],
        dataScope: 'DIRECT_REPORTS',
      },
      {
        module: 'EMPLOYEE_CENTRAL',
        subModule: 'EMPLOYMENT_INFO',
        permissions: ['EC_EMPLOYMENT_VIEW'],
        dataScope: 'DIRECT_REPORTS',
      },
      {
        module: 'PERFORMANCE',
        subModule: 'GOAL_MANAGEMENT',
        permissions: ['PERF_GOAL_VIEW', 'PERF_GOAL_CREATE', 'PERF_GOAL_APPROVE'],
        dataScope: 'DIRECT_REPORTS',
      },
      {
        module: 'PERFORMANCE',
        subModule: 'REVIEWS',
        permissions: ['PERF_REVIEW_VIEW', 'PERF_REVIEW_CREATE', 'PERF_REVIEW_EDIT'],
        dataScope: 'DIRECT_REPORTS',
      },
      {
        module: 'TIME_MANAGEMENT',
        subModule: 'TIME_OFF',
        permissions: ['TIME_OFF_VIEW', 'TIME_OFF_APPROVE', 'TIME_OFF_REJECT'],
        dataScope: 'DIRECT_REPORTS',
      },
      {
        module: 'TIME_MANAGEMENT',
        subModule: 'TIMESHEETS',
        permissions: ['TIMESHEET_VIEW', 'TIMESHEET_APPROVE'],
        dataScope: 'DIRECT_REPORTS',
      },
    ],
  },
  {
    templateCode: 'TEMPLATE_EMPLOYEE_SELF_SERVICE',
    templateName: 'Employee Self-Service',
    templateDescription: 'Basic permissions for employees to manage their own data and requests',
    templateCategory: 'EMPLOYEE',
    icon: 'User',
    color: 'purple',
    displayOrder: 3,
    isSystemTemplate: true,
    isRecommended: true,
    permissions: [
      {
        module: 'EMPLOYEE_CENTRAL',
        subModule: 'PERSONAL_DATA',
        permissions: ['EC_PERSONAL_VIEW', 'EC_PERSONAL_EDIT'],
        dataScope: 'OWN_DATA_ONLY',
      },
      {
        module: 'EMPLOYEE_CENTRAL',
        subModule: 'EMPLOYMENT_INFO',
        permissions: ['EC_EMPLOYMENT_VIEW'],
        dataScope: 'OWN_DATA_ONLY',
      },
      {
        module: 'COMPENSATION',
        subModule: 'PAYSLIPS',
        permissions: ['COMP_PAYSLIP_VIEW', 'COMP_PAYSLIP_DOWNLOAD'],
        dataScope: 'OWN_DATA_ONLY',
      },
      {
        module: 'PERFORMANCE',
        subModule: 'GOAL_MANAGEMENT',
        permissions: ['PERF_GOAL_VIEW', 'PERF_GOAL_CREATE', 'PERF_GOAL_EDIT'],
        dataScope: 'OWN_DATA_ONLY',
      },
      {
        module: 'TIME_MANAGEMENT',
        subModule: 'TIME_OFF',
        permissions: ['TIME_OFF_VIEW', 'TIME_OFF_CREATE', 'TIME_OFF_EDIT'],
        dataScope: 'OWN_DATA_ONLY',
      },
      {
        module: 'LEARNING',
        subModule: 'COURSES',
        permissions: ['LEARN_COURSE_VIEW', 'LEARN_COURSE_ENROLL'],
        dataScope: 'OWN_DATA_ONLY',
      },
    ],
  },
  {
    templateCode: 'TEMPLATE_PAYROLL_ADMIN',
    templateName: 'Payroll Administrator',
    templateDescription: 'Full payroll processing and compensation management permissions',
    templateCategory: 'FINANCE',
    icon: 'DollarSign',
    color: 'yellow',
    displayOrder: 4,
    isSystemTemplate: true,
    isRecommended: true,
    permissions: [
      {
        module: 'COMPENSATION',
        subModule: 'PAYROLL',
        permissions: ['COMP_PAYROLL_VIEW', 'COMP_PAYROLL_PROCESS', 'COMP_PAYROLL_APPROVE', 'COMP_PAYROLL_EXPORT'],
        dataScope: 'GLOBAL',
      },
      {
        module: 'COMPENSATION',
        subModule: 'SALARY',
        permissions: ['COMP_SALARY_VIEW', 'COMP_SALARY_EDIT', 'COMP_SALARY_APPROVE'],
        dataScope: 'GLOBAL',
      },
      {
        module: 'COMPENSATION',
        subModule: 'PAYSLIPS',
        permissions: ['COMP_PAYSLIP_VIEW', 'COMP_PAYSLIP_GENERATE', 'COMP_PAYSLIP_EXPORT'],
        dataScope: 'GLOBAL',
      },
      {
        module: 'EMPLOYEE_CENTRAL',
        subModule: 'EMPLOYMENT_INFO',
        permissions: ['EC_EMPLOYMENT_VIEW'],
        dataScope: 'GLOBAL',
      },
      {
        module: 'ANALYTICS',
        permissions: ['ANALYTICS_COMPENSATION_VIEW', 'ANALYTICS_COMPENSATION_EXPORT'],
        dataScope: 'GLOBAL',
      },
    ],
  },
  {
    templateCode: 'TEMPLATE_RECRUITER',
    templateName: 'Recruiter - Talent Acquisition',
    templateDescription: 'Recruiting and candidate management permissions',
    templateCategory: 'RECRUITING',
    icon: 'Briefcase',
    color: 'indigo',
    displayOrder: 5,
    isSystemTemplate: true,
    isRecommended: true,
    permissions: [
      {
        module: 'RECRUITING',
        subModule: 'JOB_POSTINGS',
        permissions: ['REC_JOBPOST_VIEW', 'REC_JOBPOST_CREATE', 'REC_JOBPOST_EDIT', 'REC_JOBPOST_DELETE'],
        dataScope: 'BUSINESS_UNIT',
      },
      {
        module: 'RECRUITING',
        subModule: 'CANDIDATES',
        permissions: ['REC_CANDIDATE_VIEW', 'REC_CANDIDATE_CREATE', 'REC_CANDIDATE_EDIT', 'REC_CANDIDATE_DELETE', 'REC_CANDIDATE_EXPORT'],
        dataScope: 'BUSINESS_UNIT',
      },
      {
        module: 'RECRUITING',
        subModule: 'APPLICATIONS',
        permissions: ['REC_APPLICATION_VIEW', 'REC_APPLICATION_REVIEW', 'REC_APPLICATION_APPROVE', 'REC_APPLICATION_REJECT'],
        dataScope: 'BUSINESS_UNIT',
      },
      {
        module: 'RECRUITING',
        subModule: 'INTERVIEWS',
        permissions: ['REC_INTERVIEW_VIEW', 'REC_INTERVIEW_CREATE', 'REC_INTERVIEW_EDIT'],
        dataScope: 'BUSINESS_UNIT',
      },
      {
        module: 'RECRUITING',
        subModule: 'OFFERS',
        permissions: ['REC_OFFER_VIEW', 'REC_OFFER_CREATE', 'REC_OFFER_EDIT'],
        dataScope: 'BUSINESS_UNIT',
      },
    ],
  },
  {
    templateCode: 'TEMPLATE_AUDITOR',
    templateName: 'System Auditor',
    templateDescription: 'Read-only access for compliance and audit purposes',
    templateCategory: 'COMPLIANCE',
    icon: 'Shield',
    color: 'red',
    displayOrder: 6,
    isSystemTemplate: true,
    isRecommended: true,
    permissions: [
      {
        module: 'EMPLOYEE_CENTRAL',
        permissions: ['EC_PERSONAL_VIEW', 'EC_EMPLOYMENT_VIEW', 'EC_AUDIT_VIEW'],
        dataScope: 'GLOBAL',
      },
      {
        module: 'COMPENSATION',
        permissions: ['COMP_PAYROLL_VIEW', 'COMP_SALARY_VIEW', 'COMP_AUDIT_VIEW'],
        dataScope: 'GLOBAL',
      },
      {
        module: 'TIME_MANAGEMENT',
        permissions: ['TIME_OFF_VIEW', 'TIMESHEET_VIEW', 'TIME_AUDIT_VIEW'],
        dataScope: 'GLOBAL',
      },
      {
        module: 'ADMIN',
        subModule: 'AUDIT_LOGS',
        permissions: ['ADMIN_AUDIT_VIEW', 'ADMIN_AUDIT_EXPORT'],
        dataScope: 'GLOBAL',
      },
      {
        module: 'ADMIN',
        subModule: 'RBAC',
        permissions: ['ADMIN_RBAC_VIEW', 'ADMIN_RBAC_AUDIT'],
        dataScope: 'GLOBAL',
      },
      {
        module: 'ANALYTICS',
        permissions: ['ANALYTICS_VIEW', 'ANALYTICS_EXPORT'],
        dataScope: 'GLOBAL',
      },
    ],
  },
  {
    templateCode: 'TEMPLATE_LEARNING_ADMIN',
    templateName: 'Learning & Development Administrator',
    templateDescription: 'Learning management system administration permissions',
    templateCategory: 'LEARNING',
    icon: 'GraduationCap',
    color: 'teal',
    displayOrder: 7,
    isSystemTemplate: true,
    isRecommended: false,
    permissions: [
      {
        module: 'LEARNING',
        subModule: 'COURSES',
        permissions: ['LEARN_COURSE_VIEW', 'LEARN_COURSE_CREATE', 'LEARN_COURSE_EDIT', 'LEARN_COURSE_DELETE', 'LEARN_COURSE_APPROVE'],
        dataScope: 'GLOBAL',
      },
      {
        module: 'LEARNING',
        subModule: 'ENROLLMENTS',
        permissions: ['LEARN_ENROLL_VIEW', 'LEARN_ENROLL_CREATE', 'LEARN_ENROLL_EDIT', 'LEARN_ENROLL_DELETE'],
        dataScope: 'GLOBAL',
      },
      {
        module: 'LEARNING',
        subModule: 'CERTIFICATIONS',
        permissions: ['LEARN_CERT_VIEW', 'LEARN_CERT_CREATE', 'LEARN_CERT_EDIT', 'LEARN_CERT_APPROVE'],
        dataScope: 'GLOBAL',
      },
      {
        module: 'ANALYTICS',
        subModule: 'LEARNING',
        permissions: ['ANALYTICS_LEARNING_VIEW', 'ANALYTICS_LEARNING_EXPORT'],
        dataScope: 'GLOBAL',
      },
    ],
  },
  {
    templateCode: 'TEMPLATE_SUCCESSION_PLANNER',
    templateName: 'Succession Planning Manager',
    templateDescription: 'Succession planning and talent pool management permissions',
    templateCategory: 'TALENT',
    icon: 'TrendingUp',
    color: 'orange',
    displayOrder: 8,
    isSystemTemplate: true,
    isRecommended: false,
    permissions: [
      {
        module: 'SUCCESSION',
        subModule: 'SUCCESSION_PLANS',
        permissions: ['SUCC_PLAN_VIEW', 'SUCC_PLAN_CREATE', 'SUCC_PLAN_EDIT', 'SUCC_PLAN_DELETE'],
        dataScope: 'BUSINESS_UNIT',
      },
      {
        module: 'SUCCESSION',
        subModule: 'TALENT_POOLS',
        permissions: ['SUCC_POOL_VIEW', 'SUCC_POOL_CREATE', 'SUCC_POOL_EDIT'],
        dataScope: 'BUSINESS_UNIT',
      },
      {
        module: 'PERFORMANCE',
        subModule: 'TALENT_REVIEW',
        permissions: ['PERF_TALENT_VIEW', 'PERF_TALENT_EDIT'],
        dataScope: 'BUSINESS_UNIT',
      },
      {
        module: 'EMPLOYEE_CENTRAL',
        permissions: ['EC_PERSONAL_VIEW', 'EC_EMPLOYMENT_VIEW'],
        dataScope: 'BUSINESS_UNIT',
      },
    ],
  },
];

export default RBAC_PERMISSION_TEMPLATES;
