import { DataSource } from 'typeorm';
import { RBACStandardRole } from '../entities/rbac-standard-role.entity';
import { RoleCategory, DataScopeLevel } from '../entities/rbac.enums';
import { RBACPermission, PermissionAction } from '../entities/rbac-permission.entity';
import { RBACRolePermission } from '../entities/rbac-role-permission.entity';
import { RBACSODPolicy, ViolationSeverity, ViolationAction } from '../entities/rbac-sod-policy.entity';

/**
 * RBAC Seed Data
 * Production-ready standard roles and permissions for enterprise HRIS system
 */

export const STANDARD_ROLES_SEED = [
  {
    roleCode: 'SYSTEM_SUPER_ADMIN',
    roleName: 'System Super Administrator',
    roleDescription: 'Unrestricted access to all system functions. For platform administrators only.',
    roleCategory: RoleCategory.SYSTEM_ADMIN,
    isSystemOwned: true,
    isModifiable: false,
    requiresDualApproval: true,
    requiresChangeJustification: true,
    hasRollbackCapability: true,
    isEmergencyAccessRole: false,
    defaultDataScope: DataScopeLevel.GLOBAL,
    canAccessSensitiveData: true,
    canExportData: true,
    canDownloadReports: true,
    canApproveTransactions: true,
    isGDPRCompliant: true,
    isSOXCompliant: true,
    isAuditableRole: true,
    displayOrder: 1,
  },
  {
    roleCode: 'TENANT_ADMIN',
    roleName: 'Tenant Administrator',
    roleDescription: 'Full administrative access within tenant boundary. Manages organizational configuration.',
    roleCategory: RoleCategory.TENANT_ADMIN,
    isSystemOwned: true,
    isModifiable: true,
    requiresDualApproval: true,
    requiresChangeJustification: true,
    hasRollbackCapability: true,
    defaultDataScope: DataScopeLevel.LEGAL_ENTITY,
    canAccessSensitiveData: true,
    canExportData: true,
    canDownloadReports: true,
    canApproveTransactions: true,
    isGDPRCompliant: true,
    isSOXCompliant: true,
    isAuditableRole: true,
    displayOrder: 2,
  },
  {
    roleCode: 'HR_ADMINISTRATOR',
    roleName: 'HR Administrator',
    roleDescription: 'Full HR system access. Manages employee data, payroll, benefits, and HR processes.',
    roleCategory: RoleCategory.HR_ADMIN,
    isSystemOwned: true,
    isModifiable: true,
    requiresDualApproval: false,
    defaultDataScope: DataScopeLevel.ORGANIZATION_HIERARCHY,
    canAccessSensitiveData: true,
    canExportData: true,
    canDownloadReports: true,
    canApproveTransactions: true,
    isGDPRCompliant: true,
    isAuditableRole: true,
    displayOrder: 3,
  },
  {
    roleCode: 'HR_MANAGER',
    roleName: 'HR Manager',
    roleDescription: 'HR operations and employee management. Limited access to sensitive data.',
    roleCategory: RoleCategory.HR_MANAGER,
    isSystemOwned: true,
    isModifiable: true,
    defaultDataScope: DataScopeLevel.DEPARTMENT,
    canAccessSensitiveData: false,
    canExportData: true,
    canDownloadReports: true,
    canApproveTransactions: true,
    isGDPRCompliant: true,
    isAuditableRole: true,
    displayOrder: 4,
  },
  {
    roleCode: 'LINE_MANAGER',
    roleName: 'Line Manager',
    roleDescription: 'Direct people management. View and manage direct reports only.',
    roleCategory: RoleCategory.LINE_MANAGER,
    isSystemOwned: true,
    isModifiable: true,
    defaultDataScope: DataScopeLevel.DIRECT_REPORTS,
    canAccessSensitiveData: false,
    canExportData: false,
    canDownloadReports: true,
    canApproveTransactions: true,
    isGDPRCompliant: true,
    maskedFields: ['salary', 'ssn', 'bankAccount'],
    displayOrder: 5,
  },
  {
    roleCode: 'PAYROLL_ADMIN',
    roleName: 'Payroll Administrator',
    roleDescription: 'Full payroll processing and financial data access.',
    roleCategory: RoleCategory.PAYROLL_ADMIN,
    isSystemOwned: true,
    isModifiable: true,
    requiresDualApproval: true,
    defaultDataScope: DataScopeLevel.ORGANIZATION_HIERARCHY,
    canAccessSensitiveData: true,
    canExportData: true,
    canDownloadReports: true,
    canApproveTransactions: true,
    isSOXCompliant: true,
    isAuditableRole: true,
    conflictingRoles: ['FINANCE_VIEWER'],
    displayOrder: 6,
  },
  {
    roleCode: 'FINANCE_VIEWER',
    roleName: 'Finance Viewer',
    roleDescription: 'Read-only access to financial reports and data.',
    roleCategory: RoleCategory.FINANCE_VIEWER,
    isSystemOwned: true,
    isModifiable: true,
    defaultDataScope: DataScopeLevel.ORGANIZATION_HIERARCHY,
    canAccessSensitiveData: true,
    canExportData: true,
    canDownloadReports: true,
    canApproveTransactions: false,
    isSOXCompliant: true,
    isAuditableRole: true,
    conflictingRoles: ['PAYROLL_ADMIN'],
    displayOrder: 7,
  },
  {
    roleCode: 'EMPLOYEE_SELF_SERVICE',
    roleName: 'Employee (Self-Service)',
    roleDescription: 'Employee self-service portal access. View and update own data only.',
    roleCategory: RoleCategory.EMPLOYEE_SELF_SERVICE,
    isSystemOwned: true,
    isModifiable: false,
    defaultDataScope: DataScopeLevel.OWN_DATA_ONLY,
    canAccessSensitiveData: false,
    canExportData: false,
    canDownloadReports: false,
    canApproveTransactions: false,
    isGDPRCompliant: true,
    displayOrder: 8,
  },
  {
    roleCode: 'AUDITOR_READ_ONLY',
    roleName: 'Auditor (Read-Only)',
    roleDescription: 'Comprehensive read-only access for audit and compliance purposes.',
    roleCategory: RoleCategory.AUDITOR,
    isSystemOwned: true,
    isModifiable: false,
    defaultDataScope: DataScopeLevel.GLOBAL,
    canAccessSensitiveData: true,
    canExportData: true,
    canDownloadReports: true,
    canApproveTransactions: false,
    isGDPRCompliant: true,
    isSOXCompliant: true,
    isAuditableRole: true,
    displayOrder: 9,
  },
  {
    roleCode: 'RECRUITER',
    roleName: 'Recruiter',
    roleDescription: 'Recruitment and applicant tracking system access.',
    roleCategory: RoleCategory.RECRUITER,
    isSystemOwned: true,
    isModifiable: true,
    defaultDataScope: DataScopeLevel.DEPARTMENT,
    canAccessSensitiveData: false,
    canExportData: true,
    canDownloadReports: true,
    canApproveTransactions: false,
    isGDPRCompliant: true,
    displayOrder: 10,
  },
  {
    roleCode: 'COMPLIANCE_OFFICER',
    roleName: 'Compliance Officer',
    roleDescription: 'Access to compliance reports and regulatory data.',
    roleCategory: RoleCategory.COMPLIANCE_OFFICER,
    isSystemOwned: true,
    isModifiable: true,
    defaultDataScope: DataScopeLevel.ORGANIZATION_HIERARCHY,
    canAccessSensitiveData: true,
    canExportData: true,
    canDownloadReports: true,
    canApproveTransactions: false,
    isGDPRCompliant: true,
    isSOXCompliant: true,
    isAuditableRole: true,
    displayOrder: 11,
  },
  {
    roleCode: 'DEPARTMENT_HEAD',
    roleName: 'Department Head',
    roleDescription: 'Department-wide management access including budgets and approvals.',
    roleCategory: RoleCategory.DEPARTMENT_HEAD,
    isSystemOwned: true,
    isModifiable: true,
    defaultDataScope: DataScopeLevel.DEPARTMENT,
    canAccessSensitiveData: false,
    canExportData: true,
    canDownloadReports: true,
    canApproveTransactions: true,
    isAuditableRole: true,
    maskedFields: ['salary', 'ssn'],
    displayOrder: 12,
  },
  {
    roleCode: 'EMERGENCY_BREAK_GLASS',
    roleName: 'Emergency Access (Break-Glass)',
    roleDescription: 'Emergency access role for critical incidents. All usage audited.',
    roleCategory: RoleCategory.SYSTEM_ADMIN,
    isSystemOwned: true,
    isModifiable: false,
    requiresDualApproval: true,
    requiresChangeJustification: true,
    isEmergencyAccessRole: true,
    defaultDataScope: DataScopeLevel.GLOBAL,
    canAccessSensitiveData: true,
    canExportData: true,
    canDownloadReports: true,
    canApproveTransactions: true,
    maxAssignmentDurationDays: 1,
    isAuditableRole: true,
    displayOrder: 99,
  },
];

export const STANDARD_PERMISSIONS_SEED = [
  // Employee Management Permissions
  {
    permissionCode: 'EMPLOYEE_PROFILE_VIEW',
    permissionName: 'View Employee Profile',
    permissionDescription: 'View employee personal and employment information',
    module: 'EMPLOYEE_MANAGEMENT',
    subModule: 'PROFILE',
    feature: 'PERSONAL_DATA',
    action: PermissionAction.VIEW,
    category: 'HR',
    isSystemPermission: true,
    riskLevel: 2,
    accessesPII: true,
    requiresAuditLog: true,
    displayOrder: 1,
  },
  {
    permissionCode: 'EMPLOYEE_PROFILE_CREATE',
    permissionName: 'Create Employee Profile',
    permissionDescription: 'Create new employee records',
    module: 'EMPLOYEE_MANAGEMENT',
    subModule: 'PROFILE',
    feature: 'PERSONAL_DATA',
    action: PermissionAction.CREATE,
    category: 'HR',
    isSystemPermission: true,
    isSensitive: true,
    riskLevel: 5,
    accessesPII: true,
    requiresAuditLog: true,
    displayOrder: 2,
  },
  {
    permissionCode: 'EMPLOYEE_PROFILE_EDIT',
    permissionName: 'Edit Employee Profile',
    permissionDescription: 'Modify employee personal and employment information',
    module: 'EMPLOYEE_MANAGEMENT',
    subModule: 'PROFILE',
    feature: 'PERSONAL_DATA',
    action: PermissionAction.EDIT,
    category: 'HR',
    isSystemPermission: true,
    isSensitive: true,
    riskLevel: 5,
    accessesPII: true,
    requiresAuditLog: true,
    displayOrder: 3,
  },
  {
    permissionCode: 'EMPLOYEE_PROFILE_DELETE',
    permissionName: 'Delete Employee Profile',
    permissionDescription: 'Permanently delete employee records',
    module: 'EMPLOYEE_MANAGEMENT',
    subModule: 'PROFILE',
    feature: 'PERSONAL_DATA',
    action: PermissionAction.DELETE,
    category: 'HR',
    isSystemPermission: true,
    isSensitive: true,
    requiresApproval: true,
    riskLevel: 9,
    accessesPII: true,
    requiresAuditLog: true,
    requiresMFA: true,
    displayOrder: 4,
  },
  {
    permissionCode: 'EMPLOYEE_SALARY_VIEW',
    permissionName: 'View Employee Salary',
    permissionDescription: 'View employee compensation data',
    module: 'EMPLOYEE_MANAGEMENT',
    subModule: 'COMPENSATION',
    feature: 'SALARY',
    action: PermissionAction.VIEW,
    category: 'PAYROLL',
    isSystemPermission: true,
    isSensitive: true,
    riskLevel: 7,
    accessesPII: true,
    accessesFinancialData: true,
    requiresAuditLog: true,
    displayOrder: 5,
  },
  {
    permissionCode: 'EMPLOYEE_SALARY_EDIT',
    permissionName: 'Edit Employee Salary',
    permissionDescription: 'Modify employee compensation',
    module: 'EMPLOYEE_MANAGEMENT',
    subModule: 'COMPENSATION',
    feature: 'SALARY',
    action: PermissionAction.EDIT,
    category: 'PAYROLL',
    isSystemPermission: true,
    isSensitive: true,
    requiresApproval: true,
    riskLevel: 9,
    accessesPII: true,
    accessesFinancialData: true,
    requiresAuditLog: true,
    requiresMFA: true,
    displayOrder: 6,
  },

  // Payroll Permissions
  {
    permissionCode: 'PAYROLL_RUN_VIEW',
    permissionName: 'View Payroll Run',
    permissionDescription: 'View payroll processing and results',
    module: 'PAYROLL',
    subModule: 'PROCESSING',
    feature: 'PAYROLL_RUN',
    action: PermissionAction.VIEW,
    category: 'PAYROLL',
    isSystemPermission: true,
    riskLevel: 5,
    accessesFinancialData: true,
    requiresAuditLog: true,
    displayOrder: 10,
  },
  {
    permissionCode: 'PAYROLL_RUN_CREATE',
    permissionName: 'Create Payroll Run',
    permissionDescription: 'Initiate payroll processing',
    module: 'PAYROLL',
    subModule: 'PROCESSING',
    feature: 'PAYROLL_RUN',
    action: PermissionAction.CREATE,
    category: 'PAYROLL',
    isSystemPermission: true,
    isSensitive: true,
    requiresApproval: true,
    riskLevel: 8,
    accessesFinancialData: true,
    requiresAuditLog: true,
    requiresMFA: true,
    displayOrder: 11,
  },
  {
    permissionCode: 'PAYROLL_RUN_APPROVE',
    permissionName: 'Approve Payroll Run',
    permissionDescription: 'Final approval for payroll processing',
    module: 'PAYROLL',
    subModule: 'PROCESSING',
    feature: 'PAYROLL_RUN',
    action: PermissionAction.APPROVE,
    category: 'PAYROLL',
    isSystemPermission: true,
    isSensitive: true,
    requiresApproval: false,
    riskLevel: 10,
    accessesFinancialData: true,
    requiresAuditLog: true,
    requiresMFA: true,
    displayOrder: 12,
  },
  {
    permissionCode: 'PAYROLL_REPORT_EXPORT',
    permissionName: 'Export Payroll Reports',
    permissionDescription: 'Download payroll reports and data',
    module: 'PAYROLL',
    subModule: 'REPORTS',
    feature: 'EXPORT',
    action: PermissionAction.EXPORT,
    category: 'PAYROLL',
    isSystemPermission: true,
    isSensitive: true,
    riskLevel: 7,
    allowsDataExport: true,
    accessesFinancialData: true,
    accessesPII: true,
    requiresAuditLog: true,
    displayOrder: 13,
  },

  // Leave Management Permissions
  {
    permissionCode: 'LEAVE_REQUEST_VIEW',
    permissionName: 'View Leave Requests',
    permissionDescription: 'View employee leave requests',
    module: 'LEAVE_MANAGEMENT',
    subModule: 'REQUESTS',
    feature: 'LEAVE_APPLICATION',
    action: PermissionAction.VIEW,
    category: 'HR',
    isSystemPermission: true,
    riskLevel: 1,
    requiresAuditLog: false,
    displayOrder: 20,
  },
  {
    permissionCode: 'LEAVE_REQUEST_APPROVE',
    permissionName: 'Approve Leave Requests',
    permissionDescription: 'Approve or reject employee leave requests',
    module: 'LEAVE_MANAGEMENT',
    subModule: 'REQUESTS',
    feature: 'LEAVE_APPLICATION',
    action: PermissionAction.APPROVE,
    category: 'HR',
    isSystemPermission: true,
    riskLevel: 3,
    requiresAuditLog: true,
    displayOrder: 21,
  },

  // Recruitment Permissions
  {
    permissionCode: 'RECRUITMENT_JOB_VIEW',
    permissionName: 'View Job Postings',
    permissionDescription: 'View recruitment job postings',
    module: 'RECRUITMENT',
    subModule: 'JOBS',
    feature: 'JOB_POSTING',
    action: PermissionAction.VIEW,
    category: 'HR',
    isSystemPermission: true,
    riskLevel: 1,
    displayOrder: 30,
  },
  {
    permissionCode: 'RECRUITMENT_JOB_CREATE',
    permissionName: 'Create Job Postings',
    permissionDescription: 'Create new job postings',
    module: 'RECRUITMENT',
    subModule: 'JOBS',
    feature: 'JOB_POSTING',
    action: PermissionAction.CREATE,
    category: 'HR',
    isSystemPermission: true,
    riskLevel: 3,
    requiresAuditLog: true,
    displayOrder: 31,
  },
  {
    permissionCode: 'RECRUITMENT_CANDIDATE_VIEW',
    permissionName: 'View Candidates',
    permissionDescription: 'View candidate applications',
    module: 'RECRUITMENT',
    subModule: 'CANDIDATES',
    feature: 'APPLICATIONS',
    action: PermissionAction.VIEW,
    category: 'HR',
    isSystemPermission: true,
    riskLevel: 2,
    accessesPII: true,
    requiresAuditLog: true,
    displayOrder: 32,
  },

  // Organization Settings Permissions
  {
    permissionCode: 'ORG_SETTINGS_RBAC_VIEW',
    permissionName: 'View RBAC Configuration',
    permissionDescription: 'View roles, permissions, and access control settings',
    module: 'ORGANIZATION_SETTINGS',
    subModule: 'RBAC',
    feature: 'ROLES_PERMISSIONS',
    action: PermissionAction.VIEW,
    category: 'ADMIN',
    isSystemPermission: true,
    riskLevel: 4,
    requiresAuditLog: true,
    displayOrder: 40,
  },
  {
    permissionCode: 'ORG_SETTINGS_RBAC_EDIT',
    permissionName: 'Edit RBAC Configuration',
    permissionDescription: 'Modify roles, permissions, and access control settings',
    module: 'ORGANIZATION_SETTINGS',
    subModule: 'RBAC',
    feature: 'ROLES_PERMISSIONS',
    action: PermissionAction.EDIT,
    category: 'ADMIN',
    isSystemPermission: true,
    isSensitive: true,
    requiresApproval: true,
    riskLevel: 10,
    requiresAuditLog: true,
    requiresMFA: true,
    displayOrder: 41,
  },
  {
    permissionCode: 'ORG_SETTINGS_COMPANY_VIEW',
    permissionName: 'View Company Settings',
    permissionDescription: 'View company profile and organizational structure',
    module: 'ORGANIZATION_SETTINGS',
    subModule: 'COMPANY',
    feature: 'PROFILE',
    action: PermissionAction.VIEW,
    category: 'ADMIN',
    isSystemPermission: true,
    riskLevel: 2,
    displayOrder: 42,
  },
  {
    permissionCode: 'ORG_SETTINGS_COMPANY_EDIT',
    permissionName: 'Edit Company Settings',
    permissionDescription: 'Modify company profile and organizational structure',
    module: 'ORGANIZATION_SETTINGS',
    subModule: 'COMPANY',
    feature: 'PROFILE',
    action: PermissionAction.EDIT,
    category: 'ADMIN',
    isSystemPermission: true,
    isSensitive: true,
    riskLevel: 7,
    requiresAuditLog: true,
    displayOrder: 43,
  },

  // Reports & Analytics Permissions
  {
    permissionCode: 'REPORTS_HR_VIEW',
    permissionName: 'View HR Reports',
    permissionDescription: 'Access HR analytics and reports',
    module: 'REPORTS',
    subModule: 'HR_ANALYTICS',
    feature: 'DASHBOARDS',
    action: PermissionAction.VIEW,
    category: 'REPORTS',
    isSystemPermission: true,
    riskLevel: 3,
    displayOrder: 50,
  },
  {
    permissionCode: 'REPORTS_HR_EXPORT',
    permissionName: 'Export HR Reports',
    permissionDescription: 'Download HR reports and analytics data',
    module: 'REPORTS',
    subModule: 'HR_ANALYTICS',
    feature: 'EXPORT',
    action: PermissionAction.EXPORT,
    category: 'REPORTS',
    isSystemPermission: true,
    isSensitive: true,
    riskLevel: 5,
    allowsDataExport: true,
    accessesPII: true,
    requiresAuditLog: true,
    displayOrder: 51,
  },
  {
    permissionCode: 'REPORTS_FINANCIAL_VIEW',
    permissionName: 'View Financial Reports',
    permissionDescription: 'Access financial reports and analytics',
    module: 'REPORTS',
    subModule: 'FINANCIAL',
    feature: 'DASHBOARDS',
    action: PermissionAction.VIEW,
    category: 'FINANCE',
    isSystemPermission: true,
    isSensitive: true,
    riskLevel: 6,
    accessesFinancialData: true,
    requiresAuditLog: true,
    displayOrder: 52,
  },

  // Audit & Compliance Permissions
  {
    permissionCode: 'AUDIT_LOG_VIEW',
    permissionName: 'View Audit Logs',
    permissionDescription: 'Access system audit logs and trails',
    module: 'AUDIT',
    subModule: 'LOGS',
    feature: 'AUDIT_TRAIL',
    action: PermissionAction.VIEW,
    category: 'AUDIT',
    isSystemPermission: true,
    riskLevel: 5,
    requiresAuditLog: true,
    displayOrder: 60,
  },
  {
    permissionCode: 'AUDIT_LOG_EXPORT',
    permissionName: 'Export Audit Logs',
    permissionDescription: 'Download audit logs for compliance',
    module: 'AUDIT',
    subModule: 'LOGS',
    feature: 'EXPORT',
    action: PermissionAction.EXPORT,
    category: 'AUDIT',
    isSystemPermission: true,
    isSensitive: true,
    riskLevel: 7,
    allowsDataExport: true,
    requiresAuditLog: true,
    displayOrder: 61,
  },
];

export const SOD_POLICIES_SEED = [
  {
    policyCode: 'SOD_PAYROLL_FINANCE_SEGREGATION',
    policyName: 'Payroll and Finance Segregation',
    policyDescription:
      'Prevents same user from processing payroll and approving financial transactions',
    conflictingRoles: ['PAYROLL_ADMIN', 'FINANCE_VIEWER'],
    conflictType: 'ROLE_ROLE',
    severity: ViolationSeverity.HIGH,
    violationAction: ViolationAction.BLOCK,
    businessRationale: 'SOX compliance requires segregation of duties for financial operations',
    riskDescription: 'Risk of fraud through unchecked financial transactions',
    complianceFrameworks: ['SOX', 'Internal Controls'],
    checkOnRoleAssignment: true,
    checkOnPermissionChange: true,
    sendAlertOnViolation: true,
  },
  {
    policyCode: 'SOD_ADMIN_AUDITOR_SEPARATION',
    policyName: 'Administrator and Auditor Separation',
    policyDescription: 'System administrators cannot also be auditors',
    conflictingRoles: ['SYSTEM_SUPER_ADMIN', 'AUDITOR_READ_ONLY'],
    conflictType: 'ROLE_ROLE',
    severity: ViolationSeverity.CRITICAL,
    violationAction: ViolationAction.BLOCK,
    businessRationale: 'Independent audit oversight requires separation from system administration',
    riskDescription: 'Risk of tampering with audit trails and logs',
    complianceFrameworks: ['SOX', 'ISO 27001', 'GDPR'],
    checkOnRoleAssignment: true,
    checkOnPermissionChange: true,
    sendAlertOnViolation: true,
  },
  {
    policyCode: 'SOD_SALARY_APPROVAL_PROCESSING',
    policyName: 'Salary Edit and Payroll Approval Separation',
    policyDescription: 'Users who edit salaries cannot approve payroll',
    conflictingPermissions: ['EMPLOYEE_SALARY_EDIT', 'PAYROLL_RUN_APPROVE'],
    conflictType: 'PERMISSION_PERMISSION',
    severity: ViolationSeverity.HIGH,
    violationAction: ViolationAction.REQUIRE_APPROVAL,
    businessRationale: 'Prevents unauthorized salary changes from being processed without review',
    riskDescription: 'Risk of fraudulent salary modifications',
    complianceFrameworks: ['SOX', 'Internal Controls'],
    checkOnRoleAssignment: true,
    checkOnPermissionChange: true,
    sendAlertOnViolation: true,
    allowExceptions: true,
  },
  {
    policyCode: 'SOD_RBAC_MODIFICATION_LIMIT',
    policyName: 'RBAC Configuration Change Control',
    policyDescription: 'RBAC modifications require dual approval',
    conflictingPermissions: ['ORG_SETTINGS_RBAC_EDIT'],
    conflictType: 'PERMISSION_PERMISSION',
    severity: ViolationSeverity.CRITICAL,
    violationAction: ViolationAction.REQUIRE_APPROVAL,
    businessRationale: 'Prevents unauthorized privilege escalation',
    riskDescription: 'Risk of unauthorized access through permission manipulation',
    complianceFrameworks: ['SOX', 'ISO 27001', 'NIST'],
    checkOnRoleAssignment: true,
    checkOnPermissionChange: true,
    performPeriodicScan: true,
    scanIntervalHours: 24,
    sendAlertOnViolation: true,
  },
];

/**
 * Seed function to populate RBAC data
 */
export async function seedRBACData(dataSource: DataSource): Promise<void> {
  const roleRepository = dataSource.getRepository(RBACStandardRole);
  const permissionRepository = dataSource.getRepository(RBACPermission);
  const sodPolicyRepository = dataSource.getRepository(RBACSODPolicy);

  console.log('🔐 Seeding RBAC Standard Roles...');
  
  // Seed roles
  for (const roleData of STANDARD_ROLES_SEED) {
    const existingRole = await roleRepository.findOne({
      where: { roleCode: roleData.roleCode },
    });

    if (!existingRole) {
      const role = roleRepository.create({
        ...roleData,
        createdBy: 'SYSTEM_SEED',
        updatedBy: 'SYSTEM_SEED',
        approvedBy: 'SYSTEM_SEED',
        approvedAt: new Date(),
        approvalStatus: 'APPROVED',
      });
      await roleRepository.save(role);
      console.log(`✅ Created role: ${roleData.roleName}`);
    } else {
      console.log(`⏭️  Role already exists: ${roleData.roleName}`);
    }
  }

  console.log('\n🔑 Seeding RBAC Permissions...');
  
  // Seed permissions
  for (const permData of STANDARD_PERMISSIONS_SEED) {
    const existingPerm = await permissionRepository.findOne({
      where: { permissionCode: permData.permissionCode },
    });

    if (!existingPerm) {
      const permission = permissionRepository.create({
        ...permData,
        createdBy: 'SYSTEM_SEED',
        updatedBy: 'SYSTEM_SEED',
      });
      await permissionRepository.save(permission);
      console.log(`✅ Created permission: ${permData.permissionName}`);
    } else {
      console.log(`⏭️  Permission already exists: ${permData.permissionName}`);
    }
  }

  console.log('\n🛡️  Seeding Segregation of Duties Policies...');
  
  // Seed SOD policies
  for (const sodData of SOD_POLICIES_SEED) {
    const existingPolicy = await sodPolicyRepository.findOne({
      where: { policyCode: sodData.policyCode },
    });

    if (!existingPolicy) {
      const policy = sodPolicyRepository.create({
        ...sodData,
        createdBy: 'SYSTEM_SEED',
        updatedBy: 'SYSTEM_SEED',
      });
      await sodPolicyRepository.save(policy);
      console.log(`✅ Created SOD policy: ${sodData.policyName}`);
    } else {
      console.log(`⏭️  SOD policy already exists: ${sodData.policyName}`);
    }
  }

  console.log('\n✅ RBAC seed data completed successfully!');
}
