import { IsString, IsEnum, IsOptional, IsBoolean, IsObject, IsArray, IsNumber } from 'class-validator';
import { ApiProperty, PartialType } from '@nestjs/swagger';
import { ReportType, ReportFormat, ReportStatus } from '../entities/report.entity';

export class CreateReportDto {
  @ApiProperty({ description: 'Report name' })
  @IsString()
  reportName: string;

  @ApiProperty({ enum: ReportType })
  @IsEnum(ReportType)
  reportType: ReportType;

  @ApiProperty({ enum: ReportFormat, default: ReportFormat.PDF })
  @IsOptional()
  @IsEnum(ReportFormat)
  format?: ReportFormat;

  @ApiProperty({ description: 'Filters', required: false })
  @IsOptional()
  @IsObject()
  filters?: Record<string, any>;

  @ApiProperty({ description: 'Parameters', required: false })
  @IsOptional()
  @IsObject()
  parameters?: Record<string, any>;

  @ApiProperty({ description: 'Generated by user ID' })
  @IsString()
  generatedBy: string;

  @ApiProperty({ description: 'Is scheduled', default: false })
  @IsOptional()
  @IsBoolean()
  isScheduled?: boolean;

  @ApiProperty({ description: 'Schedule configuration', required: false })
  @IsOptional()
  @IsObject()
  scheduleConfig?: Record<string, any>;
}

export class UpdateReportDto extends PartialType(CreateReportDto) {
  @ApiProperty({ enum: ReportStatus, required: false })
  @IsOptional()
  @IsEnum(ReportStatus)
  status?: ReportStatus;

  @ApiProperty({ description: 'File path', required: false })
  @IsOptional()
  @IsString()
  filePath?: string;

  @ApiProperty({ description: 'File URL', required: false })
  @IsOptional()
  @IsString()
  fileUrl?: string;

  @ApiProperty({ description: 'File size', required: false })
  @IsOptional()
  @IsNumber()
  fileSize?: number;

  @ApiProperty({ description: 'Error message', required: false })
  @IsOptional()
  @IsString()
  errorMessage?: string;
}

export class ReportQueryDto {
  @ApiProperty({ enum: ReportType, required: false })
  @IsOptional()
  @IsEnum(ReportType)
  reportType?: ReportType;

  @ApiProperty({ enum: ReportStatus, required: false })
  @IsOptional()
  @IsEnum(ReportStatus)
  status?: ReportStatus;

  @ApiProperty({ description: 'Generated by user ID', required: false })
  @IsOptional()
  @IsString()
  generatedBy?: string;

  @ApiProperty({ description: 'Page number', default: 1 })
  @IsOptional()
  @IsNumber()
  page?: number;

  @ApiProperty({ description: 'Items per page', default: 10 })
  @IsOptional()
  @IsNumber()
  limit?: number;
}

export class CreateReportTemplateDto {
  @ApiProperty({ description: 'Template name' })
  @IsString()
  templateName: string;

  @ApiProperty({ enum: ReportType })
  @IsEnum(ReportType)
  reportType: ReportType;

  @ApiProperty({ description: 'Description', required: false })
  @IsOptional()
  @IsString()
  description?: string;

  @ApiProperty({ description: 'Default filters', required: false })
  @IsOptional()
  @IsObject()
  defaultFilters?: Record<string, any>;

  @ApiProperty({ description: 'Default columns', required: false })
  @IsOptional()
  @IsArray()
  defaultColumns?: string[];

  @ApiProperty({ description: 'Chart configuration', required: false })
  @IsOptional()
  @IsObject()
  chartConfig?: Record<string, any>;

  @ApiProperty({ description: 'Is public', default: false })
  @IsOptional()
  @IsBoolean()
  isPublic?: boolean;

  @ApiProperty({ description: 'Created by user ID' })
  @IsString()
  createdBy: string;
}

export class UpdateReportTemplateDto extends PartialType(CreateReportTemplateDto) {}

export class GenerateReportDto {
  @ApiProperty({ description: 'Template ID', required: false })
  @IsOptional()
  @IsString()
  templateId?: string;

  @ApiProperty({ enum: ReportType })
  @IsEnum(ReportType)
  reportType: ReportType;

  @ApiProperty({ enum: ReportFormat, default: ReportFormat.PDF })
  @IsOptional()
  @IsEnum(ReportFormat)
  format?: ReportFormat;

  @ApiProperty({ description: 'Filters', required: false })
  @IsOptional()
  @IsObject()
  filters?: Record<string, any>;

  @ApiProperty({ description: 'Parameters', required: false })
  @IsOptional()
  @IsObject()
  parameters?: Record<string, any>;
}
